language: python
python:
 - "3.6.1"
install:
  - pip install codecov
# command to run tests
script:
 - python -m unittest TestTriangle
 - py.test tests/TestTriangle.py --cov=codecov

after_success:
  - codecov
